// Mocks generated by Mockito 5.4.4 from annotations
// in receipt_organizer/test/unit/services/ocr_service_retry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:google_mlkit_commons/google_mlkit_commons.dart' as _i5;
import 'package:google_mlkit_text_recognition/src/text_recognizer.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecognizedText_0 extends _i1.SmartFake
    implements _i2.RecognizedText {
  _FakeRecognizedText_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TextRecognizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextRecognizer extends _i1.Mock implements _i2.TextRecognizer {
  MockTextRecognizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TextRecognitionScript get script => (super.noSuchMethod(
        Invocation.getter(#script),
        returnValue: _i2.TextRecognitionScript.latin,
      ) as _i2.TextRecognitionScript);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i4.Future<_i2.RecognizedText> processImage(_i5.InputImage? inputImage) =>
      (super.noSuchMethod(
        Invocation.method(
          #processImage,
          [inputImage],
        ),
        returnValue: _i4.Future<_i2.RecognizedText>.value(_FakeRecognizedText_0(
          this,
          Invocation.method(
            #processImage,
            [inputImage],
          ),
        )),
      ) as _i4.Future<_i2.RecognizedText>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
