#!/bin/bash

echo "🧹 Git History Secret Removal Script"
echo "====================================="
echo ""
echo "⚠️  WARNING: This will rewrite git history!"
echo "Make sure all team members are aware before proceeding."
echo ""
echo "Step 1: Install BFG Repo Cleaner"
echo "---------------------------------"
echo "wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar"
echo ""
echo "Step 2: Create backup"
echo "---------------------"
echo "cp -r .git .git.backup"
echo ""
echo "Step 3: Remove .env files from history"
echo "---------------------------------------"
echo "java -jar bfg-1.14.0.jar --delete-files '.env.local' ."
echo "java -jar bfg-1.14.0.jar --delete-files '.env.production' ."
echo ""
echo "Step 4: Clean repository"
echo "------------------------"
echo "git reflog expire --expire=now --all"
echo "git gc --prune=now --aggressive"
echo ""
echo "Step 5: Force push (CAUTION!)"
echo "-----------------------------"
echo "git push --force --all"
echo "git push --force --tags"
