// Mocks generated by Mockito 5.4.4 from annotations
// in receipt_organizer/test/widget/capture/batch_capture_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:camera/camera.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:receipt_organizer/data/models/camera_frame.dart' as _i6;
import 'package:receipt_organizer/data/models/capture_result.dart' as _i2;
import 'package:receipt_organizer/data/models/edge_detection_result.dart'
    as _i3;
import 'package:receipt_organizer/domain/services/camera_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCaptureResult_0 extends _i1.SmartFake implements _i2.CaptureResult {
  _FakeCaptureResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEdgeDetectionResult_1 extends _i1.SmartFake
    implements _i3.EdgeDetectionResult {
  _FakeEdgeDetectionResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ICameraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockICameraService extends _i1.Mock implements _i4.ICameraService {
  @override
  _i5.Future<_i2.CaptureResult> captureReceipt({bool? batchMode = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureReceipt,
          [],
          {#batchMode: batchMode},
        ),
        returnValue: _i5.Future<_i2.CaptureResult>.value(_FakeCaptureResult_0(
          this,
          Invocation.method(
            #captureReceipt,
            [],
            {#batchMode: batchMode},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.CaptureResult>.value(_FakeCaptureResult_0(
          this,
          Invocation.method(
            #captureReceipt,
            [],
            {#batchMode: batchMode},
          ),
        )),
      ) as _i5.Future<_i2.CaptureResult>);

  @override
  _i5.Stream<_i6.CameraFrame> getPreviewStream() => (super.noSuchMethod(
        Invocation.method(
          #getPreviewStream,
          [],
        ),
        returnValue: _i5.Stream<_i6.CameraFrame>.empty(),
        returnValueForMissingStub: _i5.Stream<_i6.CameraFrame>.empty(),
      ) as _i5.Stream<_i6.CameraFrame>);

  @override
  _i5.Future<_i3.EdgeDetectionResult> detectEdges(_i6.CameraFrame? frame) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectEdges,
          [frame],
        ),
        returnValue: _i5.Future<_i3.EdgeDetectionResult>.value(
            _FakeEdgeDetectionResult_1(
          this,
          Invocation.method(
            #detectEdges,
            [frame],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.EdgeDetectionResult>.value(
            _FakeEdgeDetectionResult_1(
          this,
          Invocation.method(
            #detectEdges,
            [frame],
          ),
        )),
      ) as _i5.Future<_i3.EdgeDetectionResult>);

  @override
  _i5.Future<_i7.CameraController?> getCameraController() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCameraController,
          [],
        ),
        returnValue: _i5.Future<_i7.CameraController?>.value(),
        returnValueForMissingStub: _i5.Future<_i7.CameraController?>.value(),
      ) as _i5.Future<_i7.CameraController?>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
