import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';
import 'package:google_ml_kit/google_ml_kit.dart';

// Generate mocks for these classes
@GenerateMocks([
  TextRecognizer,
  RecognizedText, 
  TextBlock,
  TextLine
])
import 'mock_text_recognizer.mocks.dart';

// Export generated mocks for easier access
export 'mock_text_recognizer.mocks.dart';

// Note: Mock classes are now generated by build_runner
// Access them via: MockTextRecognizer, MockRecognizedText, MockTextBlock, MockTextLine

/// Test data factory for creating realistic OCR scenarios
class TestOCRData {
  /// High confidence receipt with all fields
  static RecognizedText highConfidenceReceipt() {
    final lines = [
      _createMockLine('STARBUCKS COFFEE'),
      _createMockLine('123 Main Street'),
      _createMockLine('12/06/2024 14:30'),
      _createMockLine('Latte Grande        \$4.25'),
      _createMockLine('Cookie              \$2.50'),
      _createMockLine('Subtotal            \$6.75'),
      _createMockLine('Tax                 \$0.54'),
      _createMockLine('Total               \$7.29'),
    ];
    
    final block = MockTextBlock();
    when(block.text).thenReturn(lines.map((l) => l.text).join('\n'));
    when(block.lines).thenReturn(lines);
    
    final recognized = MockRecognizedText();
    when(recognized.text).thenReturn(lines.map((l) => l.text).join(' '));
    when(recognized.blocks).thenReturn([block]);
    
    return recognized;
  }
  
  /// Low confidence receipt with missing/unclear fields
  static RecognizedText lowConfidenceReceipt() {
    final lines = [
      _createMockLine('ST@RB#CKS C0FF33'),  // Corrupted merchant name
      _createMockLine('123 M@in St'),
      _createMockLine('12/0G/Z024'),        // Corrupted date
      _createMockLine('L@tte               4.Z5'),  // Missing $ and corrupted
      _createMockLine('T0t@l               ?.?9'),  // Heavily corrupted total
    ];
    
    final block = MockTextBlock();
    when(block.text).thenReturn(lines.map((l) => l.text).join('\n'));
    when(block.lines).thenReturn(lines);
    
    final recognized = MockRecognizedText();
    when(recognized.text).thenReturn(lines.map((l) => l.text).join(' '));
    when(recognized.blocks).thenReturn([block]);
    
    return recognized;
  }
  
  /// Empty/failed OCR result
  static RecognizedText emptyResult() {
    final recognized = MockRecognizedText();
    when(recognized.text).thenReturn('');
    when(recognized.blocks).thenReturn([]);
    return recognized;
  }
  
  static MockTextLine _createMockLine(String text) {
    final line = MockTextLine();
    when(line.text).thenReturn(text);
    return line;
  }
  
  /// Create recognized text from list of strings
  static MockRecognizedText createRecognizedText(List<String> textLines) {
    final lines = textLines.map((text) => _createMockLine(text)).toList();
    
    final block = MockTextBlock();
    when(block.text).thenReturn(lines.map((l) => l.text).join('\n'));
    when(block.lines).thenReturn(lines);
    
    final recognized = MockRecognizedText();
    when(recognized.text).thenReturn(lines.map((l) => l.text).join(' '));
    when(recognized.blocks).thenReturn([block]);
    
    return recognized;
  }
}

/// Test data factory for merchant normalization tests
class MerchantTestData {
  /// Receipt with merchant name that should be normalized
  static MockRecognizedText receiptWithNormalizableMerchant() {
    return TestOCRData.createRecognizedText([
      'MCDONALDS #4521',
      '123 Main Street',
      '12/06/2024 14:30',
      'Big Mac Meal        $10.99',
      'Medium Fries        $2.50',
      'Subtotal            $13.49',
      'Tax                 $1.50',
      'Total               $14.99',
    ]);
  }

  /// Receipt with custom merchant name for testing normalization
  static MockRecognizedText customMerchantReceipt(String merchantName) {
    return TestOCRData.createRecognizedText([
      merchantName,
      '123 Main Street',
      '12/06/2024 14:30',
      'Item                $10.00',
      'Subtotal            $10.00',
      'Tax                 $0.80',
      'Total               $10.80',
    ]);
  }

  /// Receipt with clean merchant name (doesn't need normalization)
  static MockRecognizedText receiptWithCleanMerchant() {
    return TestOCRData.createRecognizedText([
      'Target',
      '456 Elm Street',
      '12/06/2024 15:45',
      'Electronics         $99.99',
      'Subtotal            $99.99',
      'Tax                 $8.00',
      'Total               $107.99',
    ]);
  }

  /// Receipt with missing merchant for testing edge cases
  static MockRecognizedText receiptWithMissingMerchant() {
    return TestOCRData.createRecognizedText([
      '12/06/2024 16:00',
      'Item                $15.00',
      'Subtotal            $15.00',
      'Tax                 $1.20',
      'Total               $16.20',
    ]);
  }

  /// Receipt with corrupted data for normalization error testing
  static MockRecognizedText receiptWithCorruptedData() {
    return TestOCRData.createRecognizedText([
      '@#$%^&*',  // Corrupted merchant
      '!@#$%^',
      '99/99/9999',
      'ERROR               $?.??',
      'Total               $?.??',
    ]);
  }
}