#!/bin/bash

echo "======================================"
echo "Receipt Organizer API Deployment"
echo "======================================"
echo ""
echo "This script will deploy your API to Vercel."
echo ""
echo "STEP 1: Login to Vercel (if needed)"
echo "Choose 'Continue with GitHub' or your preferred method"
echo ""
read -p "Press Enter to login to Vercel..."
vercel login

echo ""
echo "STEP 2: Deploy the API"
echo "When prompted:"
echo "  - Set up and deploy: Yes"
echo "  - Which scope: Choose your account"
echo "  - Link to existing project: No"
echo "  - Project name: receipt-organizer-api (or press Enter for default)"
echo "  - Directory: ./ (press Enter)"
echo "  - Override settings: No"
echo ""
read -p "Press Enter to start deployment..."
vercel

echo ""
echo "======================================"
echo "DEPLOYMENT COMPLETE!"
echo "======================================"
echo ""
echo "Your deployment URL will be shown above."
echo "It will look like: https://receipt-organizer-api-xxx.vercel.app"
echo ""
echo "NEXT STEPS:"
echo "1. Copy your deployment URL"
echo "2. Go to: https://vercel.com/dashboard"
echo "3. Click on your project"
echo "4. Go to Settings > Environment Variables"
echo "5. Add the environment variables from DEPLOYMENT.md"
echo ""
echo "Need the environment variables? They're in:"
echo "  /home/matt/FINAPP/Receipt Organizer/apps/api/DEPLOYMENT.md"
echo ""