#!/bin/bash

# CRITICAL: Update Vercel Environment Variables
# Run this script IMMEDIATELY after generating new secrets

echo "🔐 Updating Vercel Environment Variables..."
echo "⚠️  IMPORTANT: You need to update these secrets NOW!"
echo ""
echo "Step 1: Generate new secrets:"
echo "----------------------------------------"
echo "JWT_SECRET: $(openssl rand -base64 32)"
echo ""
echo "Step 2: Go to QuickBooks Developer Portal:"
echo "----------------------------------------"
echo "1. Visit: https://developer.intuit.com/app/developer/appdetail"
echo "2. Regenerate your Client Secret"
echo "3. Copy the new secret"
echo ""
echo "Step 3: Go to Upstash Console:"
echo "----------------------------------------"
echo "1. Visit: https://console.upstash.com/"
echo "2. Select your Redis database"
echo "3. Go to REST API tab"
echo "4. Regenerate the token"
echo ""
echo "Step 4: Update Vercel:"
echo "----------------------------------------"
echo "Run these commands with your NEW values:"
echo ""
echo "vercel env add QB_CLIENT_SECRET production"
echo "vercel env add KV_REST_API_TOKEN production" 
echo "vercel env add JWT_SECRET production"
echo "vercel env add XERO_CLIENT_SECRET production"
echo ""
echo "Step 5: Redeploy:"
echo "----------------------------------------"
echo "vercel --prod"
echo ""
echo "⚠️  OLD CREDENTIALS ARE COMPROMISED - DO THIS NOW!"